apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "printer.fullname" . }}
  labels:
{{ include "printer.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "printer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ default 1 .Values.maxSurge }}
      maxUnavailable: {{ default "100%" .Values.maxUnavailable }}
    type: {{ default "RollingUpdate" .Values.strategyType }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "printer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
