apiVersion: v1
kind: Service
metadata:
  name: {{ include "printer.fullname" . }}
  labels:
{{ include "printer.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.port }}-tcp
  selector:
    app.kubernetes.io/name: {{ include "printer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
